# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < https://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < https://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < https://docs.platformio.org/page/userguide/cmd_ci.html >
#
#
# Please choose one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#

jobs:
  include:
    - stage: Framework
      name: "Hello World Example"
      language: python
      python:
          - "3.8"
      sudo: false
      cache:
          directories:
              - "~/.platformio"
      env:   
        - PLATFORMIO_CI_SRC=examples/helloWorld/helloWorld.cpp
      install:
          - pip install asn1crypto
          - pip install -U platformio
          - platformio update
      script:
          - platformio ci --lib="." --board=nodemcuv2 --project-option="lib_deps=https://github.com/lorol/ESPAsyncWebServer, ArduinoJSON"

    - stage: Framework
      name: "Fetch Example"
      language: python
      python:
          - "3.8"
      sudo: false
      cache:
          directories:
              - "~/.platformio"
      env:   
        - PLATFORMIO_CI_SRC=examples/fetch/fetchExample.cpp
      install:
          - pip install asn1crypto
          - pip install -U platformio
          - platformio update
      script:
          - platformio ci --lib="." --board=nodemcuv2 --project-option="lib_deps=https://github.com/lorol/ESPAsyncWebServer, ArduinoJSON"

    - stage: Framework
      name: "configManager Example"
      language: python
      python:
          - "3.8"
      sudo: false
      cache:
          directories:
              - "~/.platformio"
      env:   
        - PLATFORMIO_CI_SRC=examples/configManager/
      install:
          - pip install asn1crypto
          - pip install -U platformio
          - platformio update
      script:
          - platformio ci --lib="." --board=nodemcuv2 --project-option="lib_deps=https://github.com/lorol/ESPAsyncWebServer, ArduinoJSON" --project-option="build_flags = -DCONFIG_PATH=src/configuration.json -DREBUILD_CONFIG"

    - stage: Framework
      name: "Time Sync Example"
      language: python
      python:
          - "3.8"
      sudo: false
      cache:
          directories:
              - "~/.platformio"
      env:   
        - PLATFORMIO_CI_SRC=examples/timeSync/timeSyncExample.cpp
      install:
          - pip install asn1crypto
          - pip install -U platformio
          - platformio update
      script:
          - platformio ci --lib="." --board=nodemcuv2 --project-option="lib_deps=https://github.com/lorol/ESPAsyncWebServer, ArduinoJSON"

    - stage: Framework
      name: "Dashboard Example"
      language: python
      python:
          - "3.8"
      sudo: false
      cache:
          directories:
              - "~/.platformio"
      env:   
        - PLATFORMIO_CI_SRC=examples/dashboard/
      install:
          - pip install asn1crypto
          - pip install -U platformio
          - platformio update
      script:
          - platformio ci --lib="." --board=nodemcuv2 --project-option="lib_deps=https://github.com/lorol/ESPAsyncWebServer, ArduinoJSON" --project-option="build_flags = -DDASHBOARD_PATH=src/dashboard.json -DREBUILD_DASHBOARD"

    - stage: GUI
      name: "Webpack Build"
      language: node_js
      node_js: 12
      env:
      script: 
        - npm run build

    - stage: GUI
      name: "ESLint"
      language: node_js
      node_js: 12
      env:
      script: 
        - npm run lint